#!/usr/bin/env python3
"""Regenerate Catbird's Open Source Licenses screen data from resolved Swift packages.

Reads Catbird.xcodeproj's Package.resolved, finds each package's checkout in the
Xcode SourcePackages directory, and writes the license and NOTICE text of every
package linked into the app to
Catbird/Features/Settings/Models/OpenSourceLicenseCatalog.swift.

Run after changing package dependencies:

    scripts/generate_open_source_licenses.py --source-packages \
        ~/Library/Developer/Xcode/DerivedData/Catbird-<hash>/SourcePackages
"""

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
RESOLVED = ROOT / "Catbird.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved"
OUTPUT = ROOT / "Catbird/Features/Settings/Models/OpenSourceLicenseCatalog.swift"
PETREL = ROOT.parent / "Petrel"

# Display metadata for linked third-party packages, keyed by Package.resolved identity.
# Catbird's own packages without a license file (BluemojiKit, CatbirdBrand, PetrelBluemoji) are omitted.
PACKAGES = {
    "adaptiveglyphkit": ("AdaptiveGlyphKit", "Josh LaCalamito", "MIT"),
    "emojikit": ("EmojiKit", "Daniel Saidi", "MIT"),
    "grdb.swift": ("GRDB", "Gwendal Roué", "MIT"),
    "lazypager": ("LazyPager", "Brian Floersch", "MIT"),
    "mantis": ("Mantis", "Yingtao Guo", "MIT"),
    "nuke": ("Nuke", "Alexander Grebenyuk", "MIT"),
    "pkl-swift": ("Pkl Swift", "Apple Inc.", "Apache 2.0"),
    "secp256k1.swift": ("secp256k1.swift", "GigaBitcoin", "MIT"),
    "semanticversion": ("SemanticVersion", "Swift Package Index", "Apache 2.0"),
    "sentry-cocoa": ("Sentry", "Sentry", "MIT"),
    "swift-asn1": ("Swift ASN.1", "Apple Inc.", "Apache 2.0"),
    "swift-async-dns-resolver": ("Swift Async DNS Resolver", "Apple Inc.", "Apache 2.0"),
    "swift-collections": ("Swift Collections", "Apple Inc.", "Apache 2.0"),
    "swift-crypto": ("Swift Crypto", "Apple Inc.", "Apache 2.0"),
    "swift-log": ("Swift Logging API", "Apple Inc.", "Apache 2.0"),
    "swift-system": ("Swift System", "Apple Inc.", "Apache 2.0"),
    "swiftcbor": ("SwiftCBOR", "Val Packett", "Unlicense"),
    "zstd": ("Zstandard", "Meta Platforms, Inc.", "BSD"),
}

# Extra notices for code vendored inside a package, relative to its checkout.
EXTRA_NOTICES = {
    "secp256k1.swift": ["Submodules/secp256k1/COPYING"],
}

LICENSE_NAMES = ["LICENSE", "LICENSE.txt", "LICENSE.md", "UNLICENSE", "COPYING"]
NOTICE_NAMES = ["NOTICE", "NOTICE.txt", "NOTICE.md"]


def first_existing(directory, names):
    for name in names:
        path = directory / name
        if path.is_file():
            return path
    return None


def swift_literal(text):
    hashes = "#"
    while f'"""{hashes}' in text or f'"{hashes}' in text:
        hashes += "#"
    return f'{hashes}"""\n{text.rstrip()}\n"""{hashes}'


def checkout_directory(checkouts, location):
    name = location.rstrip("/").split("/")[-1]
    if name.endswith(".git"):
        name = name[:-4]
    return checkouts / name


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--source-packages", required=True, type=pathlib.Path,
                        help="Xcode SourcePackages directory that contains checkouts/")
    args = parser.parse_args()
    checkouts = args.source_packages.expanduser() / "checkouts"
    pins = json.loads(RESOLVED.read_text())["pins"]

    entries = []
    for pin in pins:
        identity = pin["identity"]
        if identity not in PACKAGES:
            continue
        name, author, license_kind = PACKAGES[identity]
        directory = checkout_directory(checkouts, pin["location"])
        license_file = first_existing(directory, LICENSE_NAMES)
        if license_file is None:
            sys.exit(f"No license file for {identity} in {directory}")
        parts = [license_file.read_text()]
        notice = first_existing(directory, NOTICE_NAMES)
        if notice is not None:
            parts.append(notice.read_text())
        for extra in EXTRA_NOTICES.get(identity, []):
            parts.append((directory / extra).read_text())
        url = pin["location"].removesuffix(".git")
        entries.append((name, author, pin["state"].get("version"), url, license_kind, "\n\n".join(p.strip() for p in parts)))

    petrel_license = first_existing(PETREL, LICENSE_NAMES)
    if petrel_license is None:
        sys.exit(f"No license file for Petrel in {PETREL}")
    entries.append(("Petrel", "Josh LaCalamito", None, "https://github.com/joshlacal/Petrel", "MIT", petrel_license.read_text().strip()))
    entries.sort(key=lambda entry: entry[0].lower())

    texts = []
    lines = [
        "// Generated by scripts/generate_open_source_licenses.py. Do not edit by hand.",
        "",
        "import Foundation",
        "",
        "/// A package linked into Catbird, with the license and notice text it requires to ship.",
        "struct OpenSourceLicense: Identifiable, Hashable, Sendable {",
        "  let name: String",
        "  let author: String",
        "  let version: String?",
        "  let url: URL",
        "  let license: String",
        "  let text: String",
        "  var id: String { name }",
        "}",
        "",
        "enum OpenSourceLicenseCatalog {",
        "  static let all: [OpenSourceLicense] = [",
    ]
    for name, author, version, url, license_kind, text in entries:
        if text not in texts:
            texts.append(text)
        index = texts.index(text)
        version_literal = f'"{version}"' if version else "nil"
        lines.append(
            f'    OpenSourceLicense(name: "{name}", author: "{author}", version: {version_literal}, '
            f'url: URL(string: "{url}")!, license: "{license_kind}", text: text{index}),'
        )
    lines.append("  ]")
    for index, text in enumerate(texts):
        lines.append("")
        lines.append(f"  private static let text{index} = {swift_literal(text)}")
    lines.append("}")
    OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {len(entries)} packages to {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
